services:
    'PommProject\Foundation\QueryManager\QueryManagerInterface':
        class: 'Gnugat\PommFoundationBundle\Service\ConnectionQueryManager'
        arguments:
            - '%database_host%'
            - '%database_port%'
            - '%database_name%'
            - '%database_user%'
            - '%database_password%'

    'Gnugat\PommFoundationBundle\EventListener\ClosingConnectionListener':
        arguments:
            - '@PommProject\Foundation\QueryManager\QueryManagerInterface'
        tags:
            - { name: kernel.event_listener, event: kernel.terminate, method: onKernelTerminate }

    'Gnugat\PommFoundationBundle\Service\CreateDatabase':
        arguments:
            - '%database_host%'
            - '%database_port%'
            - '%database_name%'
            - '%database_user%'
            - '%database_password%'

    'Gnugat\PommFoundationBundle\Service\DropDatabase':
        arguments:
            - '%database_host%'
            - '%database_port%'
            - '%database_name%'
            - '%database_user%'
            - '%database_password%'

    # For legacy purpose
    gnugat_pomm_foundation.query_manager:
        alias: 'PommProject\Foundation\QueryManager\QueryManagerInterface'
