services:
    'Gnugat\PommFoundationBundle\Service\Handler\CheckDatabaseExistenceHandler':
        arguments:
            - '@Gnugat\PommFoundationBundle\Service\Handler\Internal\CheckDatabaseExistence'
