services:
    'Gnugat\PommFoundationBundle\Service\Handler\CreateDatabaseHandler':
        arguments:
            - '@Gnugat\PommFoundationBundle\Service\Handler\Internal\CheckDatabaseExistence'
            - '@Gnugat\PommFoundationBundle\Service\Handler\Internal\CreateDatabase'
