services:
    'Gnugat\PommFoundationBundle\Service\Handler\LaunchDatabaseConsoleHandler':
        arguments:
            - '@Gnugat\PommFoundationBundle\Service\Handler\Internal\CheckDatabaseExistence'
            - '@Gnugat\PommFoundationBundle\Service\Handler\Internal\LaunchDatabaseConsole'
