services:
    'Gnugat\PommFoundationBundle\Service\Handler\QueryDatabaseHandler':
        arguments:
            - '@Gnugat\PommFoundationBundle\Service\Handler\Internal\CheckDatabaseExistence'
            - '@Gnugat\PommFoundationBundle\Service\Handler\Internal\QueryDatabase'
