services:
    'Gnugat\PommFoundationBundle\Service\DropDatabase':
        arguments:
            - '%database_host%'
            - '%database_port%'
            - '%database_name%'
            - '%database_user%'
            - '%database_password%'
