services:
    'Gnugat\PommFoundationBundle\Command\CheckDatabaseExistenceCommand':
        arguments:
            - '@Gnugat\PommFoundationBundle\Service\Handler\CheckDatabaseExistenceHandler'
        tags:
            - { name: console.command, command: 'gnugat-pomm-foundation:database:check-existence' }
