services:
    'Gnugat\PommFoundationBundle\Command\CloseDatabaseConnectionsCommand':
        arguments:
            - '@Gnugat\PommFoundationBundle\Service\Handler\CloseDatabaseConnectionsHandler'
        tags:
            - { name: console.command, command: 'gnugat-pomm-foundation:database:close-connections' }
