services:
    'Gnugat\PommFoundationBundle\Command\CreateDatabaseCommand':
        arguments:
            - '@Gnugat\PommFoundationBundle\Service\CreateDatabase'
        tags:
            - { name: console.command, command: 'gnugat-pomm-foundation:database:create' }
