services:
    'Gnugat\PommFoundationBundle\Command\DumpDatabaseCommand':
        arguments:
            - '@Gnugat\PommFoundationBundle\Service\Handler\DumpDatabaseHandler'
        tags:
            - { name: console.command, command: 'gnugat-pomm-foundation:database:dump' }
